using MediaSyteem;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administation
{
    public Account currentAccount { get; set; }

    private DBLogin dblogin = new DBLogin();
    private DBPost dbpost = new DBPost();
	
	public void Add(Post Post, string Inhoud)
	{
	    dbpost.InsertMessage(Post, Inhoud);
	}

    public void Add(Map map)
    {
        dbpost.Insert(map);
    }

	public void Delete(Post Post)
	{
	    dbpost.Delete(Post.Postid.ToString());
	}

	public void Find(Post Post)
	{
		
	}

    public bool login(string username, string password)
    {
        return dblogin.loginCheck(username, password);
        
    }
    
    public void setCurrentAccount(string email)
    {
        this.currentAccount = dblogin.returnLoggedinAccount(email);
    }

    public List<Post> returnAllPosts()
    {
        List<Post> resultaat = new List<Post>();
        resultaat = dbpost.allPosts();
        return resultaat;
    }
}

