//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administation
{
	
	

	public void Add(Post Post)
	{
		
	}

	public void Delete(Post Post)
	{
		
	}

	public void Find(Post Post)
	{
		
	}

}

