//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Category
{
	public string MediaKind
	{
		get;
		set;
	}
    public string Type 
    { 
        get; 
        set; 
    }

	public Category(string Type, string MediaKind)
	{
        this.Type = Type;
        this.MediaKind = MediaKind;
	}

}

