using Oracle.DataAccess.Client;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Database
{
    private OracleConnection connectie = new OracleConnection();
    private string connectionString = "DATA SOURCE=fhictora01.fhict.local:1521/fhictora;PASSWORD=XAWdDJtZWV;USER ID=dbi314159";
    

	public Database()
	{

	}

	public void Connect()
	{
        try
        {
            connectie = new OracleConnection();
            connectie.ConnectionString = connectionString;
            connectie.Open();
        }
        catch
        {
            connectie.Close();
        }
	}

	public void DisConnect()
	{
        connectie.Close();
	}

    

}

