//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class File : Post
{
	public Category Category
	{
		get;
		set;
	}

	public  string FileLocation
	{
		get;
		set;
	}

	public Double Size
	{
		get;
		set;
	}

	public File(Account Account, DateTime Date, int Likes, Map Map, Post Post, int Reports, string Title, string Type,Category Category, string FileLocation, Double Size):base(Account,Date,  Likes, Map,Post, Reports,  Title,  Type)
	{
	}

}

