//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class File : Post
{

    public int TypeBestand
    {
        get;
        set;
    }
 
	public Category Category
	{
		get;
		set;
	}

	public  string FileLocation
	{
		get;
		set;
	}

	public long Size
	{
		get;
		set;
	}

	public File( DateTime Date, int Likes, int Map, int Post, int Reports, string Title, string Type, string FileLocation, long Size, int typeBestand):base(Date,  Likes, Map,Post, Reports,  Title,  Type)
	{
        this.Category = Category;
        this.FileLocation = FileLocation;
        this.Size = Size;
        this.TypeBestand = typeBestand;
	}

}

