//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Map
{
	public String Name
	{
		get;
		set;
	}

	public int ParentMap
	{
		get;
		set;
	}

    public int Mapid
    {
        get;
        set;
    }

    
    public Map(int mapid, string Name, int ParentMap)
    {
        this.Mapid = mapid;
        this.Name = Name;
        this.ParentMap = ParentMap;
    }

    public Map(int mapid, string name)
    {
        this.Mapid = mapid;
        this.Name = name;
    }
}

