//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Message : Post
{
	public string Content
	{
		get;
		set;
	}

	public Message(Account Account, DateTime Date, int Likes, Map Map, Post Post, int Reports, string Title, string Type, string Content):base(Account,  Date,  Likes,  Map,  Post,  Reports,  Title,  Type)
	{
        this.Content = Content;
	}

}

