//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public  class Post
{
	public Account Account
	{
		get;
		set;
	}

	public int  Map
	{
		get;
		set;
	}

	public  int ParentPost
	{
		get;
		set;
	}

	public  DateTime Date
	{
		get;
		set;
	}

	public string Type
	{
		get;
		set;
	}

	public string Title
	{
		get;
		set;
	}

	public int Reports
	{
		get;
		set;
	}

	public int Likes
	{
		get;
		set;
	}

    //Wel een parent post
	public Post( DateTime Date, int Likes, int Map, int Post, int Reports, string Title, string Type)
	{
        //this.Account = Account;
        this.Date = Date;
        this.Likes = Likes;
        this.Map = Map;
        this.ParentPost = Post;
        this.Reports = Reports;
        this.Title = Title;
        this.Type = Type;
	}

    //Wel een parent post
    public Post(DateTime Date, int Likes, int parentPost, int Reports, string Title, string Type)
    {
        //this.Account = Account;
        this.Date = Date;
        this.Likes = Likes;
        //this.Map = Map;
        this.ParentPost = parentPost;
        this.Reports = Reports;
        this.Title = Title;
        this.Type = Type;
    }

    //Geen parent post
   /* public Post( DateTime Date, int Likes, int Map,  int Reports, string Title, string Type)
    {
        this.Account = Account;
        this.Date = Date;
        this.Likes = Likes;
        this.Map = Map;
        
        this.Reports = Reports;
        this.Title = Title;
        this.Type = Type;
    }*/

    public Post( int Likes,  int Reports, string Title)
    {
        
        
        this.Likes = Likes;
        

        this.Reports = Reports;
        this.Title = Title;
        
    }

   

}

