//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Post
{
	public Account Account
	{
		get;
		set;
	}

	public Map  Map
	{
		get;
		set;
	}

	public  Post ParentPost
	{
		get;
		set;
	}

	public  DateTime Date
	{
		get;
		set;
	}

	public string Type
	{
		get;
		set;
	}

	public virtual string Title
	{
		get;
		set;
	}

	public virtual int Reports
	{
		get;
		set;
	}

	public virtual int Likes
	{
		get;
		set;
	}

	public Post(Account Account, DateTime Date, int Likes, Map Map, Post Post, int Reports, string Title, string Type)
	{
	}

}

