//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Account
{
	public virtual string Type
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

	public virtual Post Post1
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

	public Account(ICT4Event::Person Person, string Type)
	{
	}

}

