//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administation
{
	public virtual IEnumerable<Post> Post
	{
		get;
		set;
	}

	public virtual void Add(Post Post)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(Post Post)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Find(Post Post)
	{
		throw new System.NotImplementedException();
	}

}

