//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class File : Post
{
	public virtual Category Category
	{
		get;
		set;
	}

	public virtual string FileLocation
	{
		get;
		set;
	}

	public virtual Double Size
	{
		get;
		set;
	}

	public File(Category Category, string FileLocation, Double Size)
	{
	}

}

