//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Post
{
	public virtual Account Account
	{
		get;
		set;
	}

	public virtual object Map : Map
	{
		get;
		set;
	}

	public virtual Post Post
	{
		get;
		set;
	}

	public virtual DateTime Date
	{
		get;
		set;
	}

	public virtual string Type
	{
		get;
		set;
	}

	public virtual string Title
	{
		get;
		set;
	}

	public virtual int Reports
	{
		get;
		set;
	}

	public virtual int Likes
	{
		get;
		set;
	}

	public virtual Map Map
	{
		get;
		set;
	}

	public Post(Account Account, DateTime Date, int Likes, Map Map, Post Post, int Reports, string Title, string Type)
	{
	}

}

